name: Fetch RUM insights

on:
  schedule:
    - cron: '0 0 * * *'  # Run every 24 hours
  workflow_dispatch:  # Enable manual triggering

  
jobs:
  fetch-rum-insights:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch RUM insights for experiment
        uses: adobe-rnd/aem-experiments-gh-actions/fetch-rum-insights@rumdata_concurrent
        with:
          domain-key: ${{ secrets.rum_domain_key }}
          domain: 'www.maidenform.com'
          days: 30
