name: S3 to Git JSON Update

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Enable manual triggering


jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1  # Change to your desired AWS region

    - name: Download data from S3
      run: |
        aws s3 cp s3://popular-articles/articles.json popular-articles.json
      working-directory: ${{ github.workspace }}

    - name: Commit and push JSON to repository
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add popular-articles.json
        git commit -m "Update JSON data"
        git push
      working-directory: ${{ github.workspace }}
